### ISSUE TITLE
AddressSanitizer: SEGV on unknown address

### ISSUE THREAD

**Issue by evverx** [libbpf/libbpf#482]
```sh
./scripts/build-fuzzers.sh
wget -O oss-fuzz-41410 https://oss-fuzz.com/download?testcase_id=5338681456590848
./out/bpf-object-fuzzer oss-fuzz-41410
```
```sh
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 971673186
INFO: Loaded 1 modules   (10860 inline 8-bit counters): 10860 [0x6f2200, 0x6f4c6c),
INFO: Loaded 1 PC tables (10860 PCs): 10860 [0x680640,0x6aad00),
./out/bpf-object-fuzzer: Running 1 inputs 1 time(s) each.
Running: oss-fuzz-41410
AddressSanitizer:DEADLYSIGNAL
=================================================================
==96632==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000004 (pc 0x0000005f7330 bp 0x7fff3ea0ed80 sp 0x7fff3ea0ed40 T0)
==96632==The signal is caused by a READ memory access.
==96632==Hint: address points to the zero page.
    #0 0x5f7330 in btf_kind /home/vagrant/libbpf/src/./btf.h:402:9
    #1 0x5f7330 in btf__align_of /home/vagrant/libbpf/src/btf.c:642:15
    #2 0x5f7565 in btf__align_of /home/vagrant/libbpf/src/btf.c:666:12
    #3 0x5985b4 in bpf_object__collect_externs /home/vagrant/libbpf/src/libbpf.c:3697:22
    #4 0x55ea61 in bpf_object_open /home/vagrant/libbpf/src/libbpf.c:7107:16
    #5 0x55efbe in bpf_object__open_mem /home/vagrant/libbpf/src/libbpf.c:7171:20
    #6 0x553ee9 in LLVMFuzzerTestOneInput /home/vagrant/libbpf/fuzz/bpf-object-fuzzer.c:16:8
    #7 0x450f99 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/vagrant/libbpf/out/bpf-object-fuzzer+0x450f99)
    #8 0x431a3f in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/vagrant/libbpf/out/bpf-object-fuzzer+0x431a3f)
    #9 0x4396fe in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/vagrant/libbpf/out/bpf-object-fuzzer+0x4396fe)
    #10 0x428ba6 in main (/home/vagrant/libbpf/out/bpf-object-fuzzer+0x428ba6)
    #11 0x7feac47e155f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
    #12 0x7feac47e160b in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2d60b)
    #13 0x428bf4 in _start (/home/vagrant/libbpf/out/bpf-object-fuzzer+0x428bf4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/vagrant/libbpf/src/./btf.h:402:9 in btf_kind
==96632==ABORTING
```

**Comment by anakryiko** [comment]
Should be addressed by https://github.com/libbpf/libbpf/issues/617

**Comment by evverx** [comment]
OSS-Fuzz say it's gone: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41410. Closing.
