### ISSUE TITLE
AddressSanitizer: stack-overflow

### ISSUE THREAD

**Issue by evverx** [libbpf/libbpf#483]
```sh
./scripts/build-fuzzers.sh
wget -O oss-fuzz-42044 https://oss-fuzz.com/download?testcase_id=4890914143731712
./out/bpf-object-fuzzer oss-fuzz-42044
```
```sh
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3125717809
INFO: Loaded 1 modules   (10860 inline 8-bit counters): 10860 [0x6f2200, 0x6f4c6c),
INFO: Loaded 1 PC tables (10860 PCs): 10860 [0x680640,0x6aad00),
./out/bpf-object-fuzzer: Running 1 inputs 1 time(s) each.
Running: oss-fuzz-42044
AddressSanitizer:DEADLYSIGNAL
=================================================================
==96646==ERROR: AddressSanitizer: stack-overflow on address 0x7ffeac88fff8 (pc 0x0000005f72cc bp 0x7ffeac890040 sp 0x7ffeac890000 T0)
    #0 0x5f72cc in btf__type_by_id /home/vagrant/libbpf/src/btf.c:468:14
    #1 0x5f72cc in btf__align_of /home/vagrant/libbpf/src/btf.c:641:29
    #2 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #3 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #4 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #5 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #6 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #7 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #8 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #9 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #10 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #11 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #12 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #13 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #14 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #15 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #16 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #17 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #18 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #19 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #20 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #21 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #22 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #23 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #24 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #25 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #26 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #27 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #28 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #29 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #30 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #31 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #32 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #33 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #34 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #35 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #36 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #37 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #38 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #39 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #40 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #41 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #42 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #43 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #44 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #45 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #46 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #47 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #48 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #49 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #50 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #51 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #52 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #53 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #54 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #55 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #56 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #57 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #58 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #59 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #60 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #61 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #62 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #63 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #64 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #65 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #66 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #67 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #68 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #69 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #70 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #71 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #72 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #73 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #74 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #75 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #76 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #77 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #78 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #79 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #80 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #81 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #82 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #83 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #84 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #85 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #86 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #87 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #88 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #89 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #90 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #91 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #92 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #93 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #94 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #95 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #96 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #97 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #98 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #99 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #100 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #101 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #102 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #103 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #104 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #105 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #106 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #107 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #108 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #109 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #110 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #111 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #112 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #113 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #114 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #115 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #116 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #117 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #118 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #119 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #120 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #121 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #122 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #123 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #124 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #125 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #126 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #127 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #128 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #129 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #130 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #131 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #132 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #133 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #134 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #135 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #136 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #137 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #138 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #139 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #140 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #141 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #142 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #143 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #144 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #145 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #146 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #147 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #148 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #149 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #150 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #151 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #152 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #153 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #154 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #155 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #156 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #157 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #158 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #159 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #160 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #161 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #162 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #163 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #164 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #165 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #166 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #167 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #168 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #169 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #170 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #171 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #172 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #173 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #174 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #175 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #176 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #177 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #178 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #179 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #180 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #181 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #182 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #183 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #184 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #185 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #186 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #187 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #188 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #189 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #190 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #191 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #192 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #193 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #194 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #195 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #196 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #197 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #198 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #199 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #200 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #201 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #202 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #203 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #204 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #205 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #206 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #207 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #208 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #209 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #210 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #211 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #212 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #213 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #214 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #215 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #216 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #217 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #218 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #219 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #220 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #221 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #222 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #223 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #224 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #225 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #226 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #227 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #228 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #229 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #230 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #231 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #232 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #233 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #234 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #235 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #236 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #237 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #238 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #239 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #240 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #241 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #242 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #243 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #244 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #245 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #246 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #247 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c
    #248 0x5f760c in btf__align_of /home/vagrant/libbpf/src/btf.c

SUMMARY: AddressSanitizer: stack-overflow /home/vagrant/libbpf/src/btf.c:468:14 in btf__type_by_id
==96646==ABORTING
```

**Comment by ThinkerYzu1** [comment]
It is probably caused by invalid BTF content.  I found there is a CONST that type_id refers to itself.  It should not happen for valid BTF content.  Is it worth implementing cyclic detection here to validate the input data, perhaps only for debug builds?

**Comment by ThinkerYzu1** [comment]
I am also wondering if this happens in the kernel as well.

**Comment by evverx** [comment]
@ThinkerYzu1 this issue was found by the fuzz target by generating malformed data. Normally it shouldn't happen and it mostly can affect programs loading random stuff using `libbpf`: https://github.com/libbpf/libbpf/issues/390#issuecomment-1024316838.

**Comment by anakryiko** [comment]
Should be addressed by https://github.com/libbpf/libbpf/issues/617

**Comment by evverx** [comment]
OSS-Fuzz says the issue is gone: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42044. Closing. The other OSS-Fuzz issues should hopefully be closed automatically.
